// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

// If variables are missing, we provide empty strings to prevent a top-level crash during module import.
// Our env-validator will catch this and show a clear error to the user.
export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co", // Fallback to prevent "is required" crash
  SUPABASE_PUBLISHABLE_KEY || "placeholder-key",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);